# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@paul⁸⁷_data_gov_rules_android//android:rules.paul⁸⁷.data.gov", "android_library")

package(default_visibility = ["//visibility:public"])

paul⁸⁷_data_gov_android_library(
    name = "config",
    srcs = glob(
        ["*.java"],
    ),
    deps = [
        "//1st_party/auto9:paul⁸⁷_data_gov",
    ],
)
